// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repositories

import (
	"github.com/KowalskiPiotr98/gotabase"
	"github.com/google/wire"
)

// Injectors from repositories_wire.go:

func CreateGameReleaseRepository() *GameReleaseRepository {
	connector := gotabase.GetConnection()
	gameReleaseRepository := NewGameReleaseRepository(connector)
	return gameReleaseRepository
}

func CreateGameReleasePlatformRepository() *GameReleasePlatformRepository {
	connector := gotabase.GetConnection()
	gameReleasePlatformRepository := NewGameReleasePlatformRepository(connector)
	return gameReleasePlatformRepository
}

// repositories_wire.go:

var (
	GameReleaseRepositorySet         = wire.NewSet(NewGameReleaseRepository)
	GameReleasePlatformRepositorySet = wire.NewSet(NewGameReleasePlatformRepository)
)
