// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controllers

import (
	"github.com/Geepr/game/repositories"
	"github.com/KowalskiPiotr98/gotabase"
	"github.com/google/wire"
)

// Injectors from controllers_wire.go:

func CreateGameController() *GameController {
	connector := gotabase.GetConnection()
	gameRepository := repositories.NewGameRepository(connector)
	gameController := NewGameController(gameRepository)
	return gameController
}

func CreatePlatformController() *PlatformController {
	connector := gotabase.GetConnection()
	platformRepository := repositories.NewPlatformRepository(connector)
	platformController := NewPlatformController(platformRepository)
	return platformController
}

func CreateGameReleaseController() *GameReleaseController {
	connector := gotabase.GetConnection()
	gameReleaseRepository := repositories.NewGameReleaseRepository(connector)
	gameReleaseController := NewGameReleaseController(gameReleaseRepository)
	return gameReleaseController
}

func CreateGameReleasePlatformController() *GameReleasePlatformController {
	connector := gotabase.GetConnection()
	gameReleasePlatformRepository := repositories.NewGameReleasePlatformRepository(connector)
	gameReleasePlatformController := NewGameReleasePlatformController(gameReleasePlatformRepository)
	return gameReleasePlatformController
}

// controllers_wire.go:

var (
	GameControllerSet                = wire.NewSet(NewGameController, repositories.GameRepositorySet)
	PlatformControllerSet            = wire.NewSet(NewPlatformController, repositories.PlatformRepositorySet)
	GameReleaseControllerSet         = wire.NewSet(NewGameReleaseController, repositories.GameReleaseRepositorySet)
	GameReleasePlatformControllerSet = wire.NewSet(NewGameReleasePlatformController, repositories.GameReleasePlatformRepositorySet)
)
