// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controllers

import (
	"github.com/Geepr/game/repositories"
	"github.com/KowalskiPiotr98/gotabase"
	"github.com/google/wire"
)

// Injectors from controllers_wire.go:

func CreateGameReleaseController() *GameReleaseController {
	connector := gotabase.GetConnection()
	gameReleaseRepository := repositories.NewGameReleaseRepository(connector)
	gameReleaseController := NewGameReleaseController(gameReleaseRepository)
	return gameReleaseController
}

func CreateGameReleasePlatformController() *GameReleasePlatformController {
	connector := gotabase.GetConnection()
	gameReleasePlatformRepository := repositories.NewGameReleasePlatformRepository(connector)
	gameReleasePlatformController := NewGameReleasePlatformController(gameReleasePlatformRepository)
	return gameReleasePlatformController
}

// controllers_wire.go:

var (
	GameReleaseControllerSet         = wire.NewSet(NewGameReleaseController, repositories.GameReleaseRepositorySet)
	GameReleasePlatformControllerSet = wire.NewSet(NewGameReleasePlatformController, repositories.GameReleasePlatformRepositorySet)
)
