// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controllers

import (
	"github.com/Geepr/game/repositories"
	"github.com/KowalskiPiotr98/gotabase"
	"github.com/google/wire"
)

// Injectors from controllers_wire.go:

func CreateGameController() *GameController {
	connector := gotabase.GetConnection()
	gameRepository := repositories.NewGameRepository(connector)
	gameController := NewGameController(gameRepository)
	return gameController
}

// controllers_wire.go:

var (
	GameControllerSet = wire.NewSet(NewGameController, repositories.GameRepositorySet)
)
